#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with superstitious messages using case

counter=1
while [ "$counter" -le 20 ]
do
    case "$counter" in
        4)
            echo -e "4\nbad luck from China"
            ;;
        9)
            echo -e "9\nbad luck from Japan"
            ;;
        17)
            echo -e "17\nbad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    counter=$((counter + 1))
done
