#!/usr/bin/env bash
# This script lists directory contents displaying only the part after the first dash

for file in *
do
    if [ -e "$file" ]
    then
        echo "$file" | cut -d '-' -f 2-
    fi
done
