#!/bin/bash
printf '%o\n' "$(( $(w=$(echo "${WATER}" | tr 'water' '01234')
res=0
for ((i=0; i<${#w}; i++)); do
res=$((res * 5 + ${w:i:1}))
done
echo $res) + $(s=$(echo "${STIR//./}" | tr 'stir' '0123')
res=0
for ((i=0; i<${#s}; i++)); do
res=$((res * 4 + ${s:i:1}))
done
echo $res) ))" | tr '01234567' 'bestchol'
