#!/bin/bash
printf '%o\n' "$(( (5#$(echo "${WATER:0:5}" | tr 'water' '01234') * 5**${#WATER:5} + 5#$(echo "${WATER:5}" | tr 'water' '01234')) + 4#$(echo "${STIR//./}" | tr 'stir' '0123') ))" | tr '01234567' 'bestchol'
