#!/usr/bin/env bash
# This script runs indefinitely and survives SIGTERM signals using trap

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
